spring:
  jpa:
    hibernate:
      ddl-auto: none
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/alunos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8087
logging:
  level:
    br.com.springbatch.estudo: DEBUG
itemsPerChunk: 5
